[project]
name = "mcp-sentiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio[mcp]>=5.29.1",
    "smolagents>=1.16.1",
    "textblob>=0.19.0",
]
